### ISSUE TITLE
Provide alternate CLI examples for pushing to docker.io

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka-platform-guide#556] opened 2021-02-08 15:11 UTC
### Short description

Provide alternate CLI examples for pushing to docker.io

### Details

In some cases, developers may prefer to use docker.io. The following maven command worked:

`mvn -Ddocker.push.username=<docker-username> -Ddocker.push.password=<docker-password> -Ddocker.registry=docker.io/<docker-username> clean package docker:push`

**Comment by patriknw** [comment] 2021-02-08 15:40
@mckeeh3 isn't this a duplicate of https://github.com/akka/akka-platform-guide/issues/550 ?

**Comment by mckeeh3** [comment] 2021-02-08 17:27
Yes, sorry, I should have updated #550.

**Closed** 2021-02-09 07:45 UTC
