### ISSUE TITLE
Add link to tutorial sample zip corresponding to the current section

### ISSUE THREAD

**Issue by octonato** [akka/akka-platform-guide#232] opened 2020-10-02 10:13 UTC
UPDATE: 

Current idea is to add a link to the tutorial sample corresponding to the step users is at the moment. 

Run section should have enough information about which parts are needed. 

See old description below and comments for context.

---

> We can then remove it from here, but add a link or a note saying: Before continue, make sure you started the containers and created the database.

There could be a section at the beginning of each step of the tutorial listing what do you need in order to follow that step with as little interruptions as possible. E.g.:

```
To complete this step of the tutorial your need:

1. this and that tool installed and running
2. the database with schema and tables created as explained in xref:foo.adoc
3. the codebase as presented in the previous step (or download it from _here_)
```

_Originally posted by @ignasi35 in https://github.com/akka/akka-platform-guide/pull/220#discussion_r498256387_

**Comment by patriknw** [comment] 2020-10-02 14:45
I don't think we should bother the user with "installed and running", and "tables created" until the Run section.

> the codebase as presented in the previous step (or download it from _here_)

That can be good to add, when we have the source downloads. Each step (before Running) should also have a link to the download in case they failed to follow the instructions (or just not want to).

**Comment by octonato** [comment] 2020-10-05 07:15
In that case, I don't think there anything else to add, because the Run section is already expected to be comprehensive. 

We can indeed add the link to the zip file when we have it. 

I will rename the ticket here and to reflect that.

**Comment by ignasi35** [comment] 2020-10-05 09:16
So this is now a duplicate of #61, or is there any extra scope?

**Comment by patriknw** [comment] 2020-10-05 09:40
duplicate

**Closed by patriknw** 2020-10-05 09:40 UTC
